checksumBehavior: update

injectEnvironmentFiles:
  - .env.yarn
  - .env.yarn.devnet?

nodeLinker: node-modules

npmScopes:
  coinweb:
    npmRegistryServer: "https://npm.coinweb.io/"

yarnPath: .yarn/releases/yarn-4.6.0.cjs
